### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by iranmeba** [timoschlueter/nightscout-librelink-up#114]
Hi there,

I have been using this for about 2 years now and recently encountered a new error message in the logs. 

TypeError: Cannot read properties of null (reading 'FactoryTimestamp')
     at createFormattedMeasurements (/usr/src/app/src/index.ts:297:69)
     at uploadToNightScout (/usr/src/app/src/index.ts:332:50)
     at main (/usr/src/app/src/index.ts:154:11)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)

Any idea what may be going on?

Thanks

**Comment by timoschlueter** [comment]
Do you still have this issue? There is a new release with better error handling and more plausible messages.
