### ISSUE TITLE
Crash when fetching data "TypeError: resp.data.pop is not a function"

### ISSUE THREAD

**Issue by aleb** [timoschlueter/nightscout-librelink-up#154]
Using the latest "latest" docker image:
```
$ docker pull timoschlueter/nightscout-librelink-up
Using default tag: latest
latest: Pulling from timoschlueter/nightscout-librelink-up
Digest: sha256:76e96bc901577a32a801eb3f31e491e1a074bab556345f244419148fee0bd2cc
Status: Image is up to date for timoschlueter/nightscout-librelink-up:latest
docker.io/timoschlueter/nightscout-librelink-up:latest
```

```
$ docker compose logs nightscout-librelinkup  -f
nightscout-librelinkup  | 
nightscout-librelinkup  | > nightscout-librelink-up@2.7.0 start-heroku
nightscout-librelinkup  | > node dist/index.js
nightscout-librelinkup  | 
nightscout-librelinkup  | [info]: Starting cron schedule: */1 * * * *
nightscout-librelinkup  | [info]: renew token
nightscout-librelinkup  | [info]: Logged in to LibreLink Up
nightscout-librelinkup  | [debug]: authenticatedHttpHeaders: {"User-Agent":"Mozilla/5.0 (iPhone; CPU OS 17_4.1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/17.4.1 Mobile/10A5355d Safari/8536.25","Content-Type":"application/json;charset=UTF-8","version":"4.10.0","product":"llu.ios","Authorization":"..."}
nightscout-librelinkup  | [info]: Found 1 LibreLink Up connection.
nightscout-librelinkup  | [info]: -> The following connection will be used: XXX (Patient-ID: XXX)
nightscout-librelinkup  | [debug]: authenticatedHttpHeaders: {"User-Agent":"Mozilla/5.0 (iPhone; CPU OS 17_4.1 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/17.4.1 Mobile/10A5355d Safari/8536.25","Content-Type":"application/json;charset=UTF-8","version":"4.10.0","product":"llu.ios","Authorization":"XXX"}
nightscout-librelinkup  | /usr/src/app/dist/nightscout/apiv1.js:30
nightscout-librelinkup  |         return resp.data.pop();
nightscout-librelinkup  |                          ^
nightscout-librelinkup  | 
nightscout-librelinkup  | TypeError: resp.data.pop is not a function
nightscout-librelinkup  |     at Client.lastEntry (/usr/src/app/dist/nightscout/apiv1.js:30:26)
nightscout-librelinkup  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nightscout-librelinkup  |     at async createFormattedMeasurements (/usr/src/app/dist/index.js:236:47)
nightscout-librelinkup  |     at async uploadToNightScout (/usr/src/app/dist/index.js:257:35)
nightscout-librelinkup  |     at async main (/usr/src/app/dist/index.js:129:5)
nightscout-librelinkup  | 
nightscout-librelinkup  | Node.js v20.15.0
nightscout-librelinkup exited with code 1
```

**Comment by robster7674** [comment]
Seeing this on Northflank too:
```
2025-01-30T07:27:02.202739924Z stderr F /usr/src/app/dist/nightscout/apiv1.js:30
2025-01-30T07:27:02.202799097Z stderr F         return resp.data.pop();
2025-01-30T07:27:02.202803351Z stderr F                          ^
2025-01-30T07:27:02.202806231Z stderr F 
2025-01-30T07:27:02.202809084Z stderr F TypeError: resp.data.pop is not a function
2025-01-30T07:27:02.202812475Z stderr F     at Client.lastEntry (/usr/src/app/dist/nightscout/apiv1.js:30:26)
2025-01-30T07:27:02.202816307Z stderr F     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2025-01-30T07:27:02.202819154Z stderr F     at async createFormattedMeasurements (/usr/src/app/dist/index.js:253:47)
2025-01-30T07:27:02.202821933Z stderr F     at async uploadToNightScout (/usr/src/app/dist/index.js:274:35)
2025-01-30T07:27:02.202824739Z stderr F     at async main (/usr/src/app/dist/index.js:143:5)
2025-01-30T07:27:02.202826983Z stderr F 
2025-01-30T07:27:02.202829569Z stderr F Node.js v20.18.1
```

**Comment by robster7674** [comment]
Northflank support was superb, this was indeed due to a MongoDB issue.
